### ISSUE TITLE
Checklist for 0.0.1

### ISSUE THREAD

**Issue by karjac14** [DavryKarlohoun/gui#4]
**Release 0.0.1**
- [x] `develop` from Master 0.0.0
  - [x] `feature--login-page` (Terry) signup.html
  - [x] `feature--signup-page` (Terry)
  - [ ] `feature--login-fail` (Terry)
  - [x] `feature--header` (Terry) index.html
  - [ ] `feature--home-page` (Karlo)
  - [ ] `feature--question-and-answer-page` (Karlo)
  - [ ] `feature--ask-question-page` (Karlo)
- [ ] `ng-route` them! (Friday)
- [ ]  Bump package-bower-json, FireBase Deploy
- [ ]  Merge to Master

**Release 0.0.2**
- [ ] Get and Post API (Saturday)
  - [ ] Create Account
    - [ ] $http.post json
    - [ ] `.then` to homepage
  - [ ] Log-in
    - [ ] $http.post json
    - [ ] `.then` to homepage
    - [ ] `.then` failed log-in
  - [ ] Home-page
    - [ ] $http.get Top Questions
    - [ ] Display Questions
- [ ] Question Page
  - [ ] $http.get Questions and Answers
  - [ ] Display Questions and Answers
- [ ] Ask New Question Page
  - [ ] $http.post new question
  - [ ] to question page

**Release 0.0.3**
- [ ] CSS reloaded
